name: 'Code checks'

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['8.1', '8.2', '8.3']

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        coverage: xdebug

    - name: Composer install
      run: composer install --no-progress

    - name: Run tests
      run: vendor/bin/phpunit

  phpspec:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['8.1', '8.2', '8.3']

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        coverage: none

    - name: Composer install
      run: composer install --no-progress

    - name: Run phpspec
      run: vendor/bin/phpspec run --config=phpspec.yml --no-interaction -vvv

  code_style:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['8.1']

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        coverage: xdebug

    - name: Composer install
      run: composer install --no-progress

    - name: Run php-cs-fixer
      run: vendor/bin/php-cs-fixer check --config=.php_cs.dist.php --verbose --diff

  phpstan:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['8.1']

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        coverage: xdebug

    - name: Composer install
      run: composer install --no-progress

    - name: Run phpstan
      run: vendor/bin/phpstan analyse -c phpstan.neon

  dependencies:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['8.1']

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        coverage: xdebug

    - name: Composer install
      run: composer install --no-progress

    - name: Run dependency analyzer
      run: vendor/bin/composer-dependency-analyser
